### PR TITLE
Re-do as mdbook

### PR DESCRIPTION
**Pull request by brkydnc**
Hi, I saw the issue #1 and decided to make an mdbook. It would be great if you accepted and served on github-pages :)

Some notes about the book:
* All code blocks are easy to run in playground
* Code blocks that fail to compile are supported with Ferris visuals
* A part of `README.md` is deleted. 
* The following lines aren't in the book (I couldn't find where to add them):
```
// Written in 2020 by Rain <rain@sunshowers.io>
//
// To the extent possible under law, the author(s) have dedicated all copyright and related and
// neighboring rights to this software to the public domain worldwide. This software is distributed
// without any warranty.
//
// You should have received a copy of the CC0 Public Domain Dedication along with this software. If
// not, see <http://creativecommons.org/publicdomain/zero/1.0/>.
```

### CODE REVIEW

**Comment by sunshowers** [comment]
Hi -- I really really apologize for missing this. I wasn't well at that time and am only now getting back into the groove of things.

Is there a place I can view the running mdbook example?

**Comment by brkydnc** [comment]
Hey! No problem.

You will need [mdbook](https://github.com/rust-lang/mdBook) tool before you view the book. Just clone my fork and run `mdbook serve`.

**Comment by brkydnc** [comment]
Hey! No problem.

You will need to install [mdbook](https://github.com/rust-lang/mdBook) before you view the book. Just run `mdbook serve` and view it at localhost. Please let me know how you feel about it!

**Comment by sunshowers** [comment]
Thank you!!! Looks great. I've also set up CI.

**Pull request merged**
